version: 2.1
orbs:
  terraform: mafuyuk/terraform@dev:b601ef1

workflows:
  verification:
    jobs:
      - terraform/init:
          executor:
            terraform/default:
                tag: 0.11.11
      - terraform/fmt:
          requires:
            - terraform/init
      - terraform/validate:
          requires:
            - terraform/init
  nightry:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - terraform/init
      - terraform/fmt:
          requires:
            - terraform/init
      - terraform/validate:
          requires:
            - terraform/init