version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:a77add3

workflows:
  deploy:
    jobs:
      - terraform/plan
      - hold:
          type: approval
          requires:
            - plan
      - terraform/apply:
          requires:
            - hold