version: 2.1
orbs:
  terraform: mafuyuk/terraform@0.6.1
workflows:
  build:
    triggers:
      - schedule:
          cron: "0 1 * * *"
    jobs:
      - terraform/validate
      - terraform/plan:
          name: stg-plan
          workspace: stg
          filters:
            branches:
              only: master
          requires:
            - terraform/validate
      - terraform/plan:
          name: prod-plan
          filters:
            tags:
              only: /v.*/
          requires:
            - terraform/validate
      - approval:
          requires:
            - prod-plan
          type: approval
      - terraform/apply:
          name: stg-apply
          requires:
            - stg-plan
          workspace: stg
      - terraform/apply:
          name: prod-apply
          requires:
            - approval