version: 2.1
orbs:
  terraform: mafuyuk/terraform@dev:05c1125

master_filter: &master_filter
  branches:
    only: master

terraform_executor: &terraform_executor
  name: terraform/default
  tag: 0.11.11

workflows:
  delivery:
    jobs:
      - terraform/init:
          name: init
          executor: *terraform_executor
          workspace: stg
          filters: *master_filter
      - terraform/fmt:
          name: fmt
          executor: *terraform_executor
          requires:
            - init
          filters: *master_filter
      - terraform/validate:
          name: validate
          executor: *terraform_executor
          requires:
            - init
          filters: *master_filter
      - terraform/plan:
          name: plan
          executor: *terraform_executor
          workspace: stg
          requires:
            - fmt
            - validate
          filters: *master_filter
      - terraform/apply:
          name: plan
          executor: *terraform_executor
          workspace: stg
          requires:
            - plan
          filters: *master_filter
