version: 2.1
orbs:
  terraform: mafuyuk/terraform@dev:b601ef1
workflows:
  verification:
    jobs:
      - terraform/fmt
      - terraform/validate
  nightry:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - terraform/fmt
      - terraform/validate