version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:d7565bd
  aws-cli: circleci/aws-cli@0.1.9

workflows:
  test:
    jobs:
      - terraform/init
      - terraform/plan:
          requires:
            - init
