version: 2.1
orbs:
  terraform: mafuyuk/terraform@dev:b601ef1

terraform_executor: &terraform_executor
  executor:
    name: terraform/default
    tag: 0.11.11

workflows:
  verification:
    jobs:
      - terraform/init:
          executor: *terraform_executor
      - terraform/fmt:
          executor: *terraform_executor
          requires:
            - terraform/init
      - terraform/validate:
          executor: *terraform_executor
          requires:
            - terraform/init
  nightry:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - terraform/init:
          executor: *terraform_executor
      - terraform/fmt:
          executor: *terraform_executor
          requires:
            - terraform/init
      - terraform/validate:
          executor: *terraform_executor
          requires:
            - terraform/init