version: 2.1
orbs:
  terraform: mafuyuk/terraform@dev:05c1125

master_filter: &master_filter
  branches:
    only: master

release_filter: &release_filter
  tags:
    only: /^v[0-9](\.[0-9]){2}$/
  branches:
    ignore: /.*/

terraform_executor: &terraform_executor
  name: terraform/default
  tag: 0.11.11

workflows:
  integration:
    jobs:
      - terraform/init:
          name: init
          executor: *terraform_executor
      - terraform/fmt:
          name: fmt
          executor: *terraform_executor
          requires:
            - init
      - terraform/validate:
          name: validate
          executor: *terraform_executor
          requires:
            - init
  delivery:
    jobs:
      - terraform/init:
          name: init
          executor: *terraform_executor
          workspace: stg
      - terraform/fmt:
          name: fmt
          executor: *terraform_executor
          requires:
            - init
      - terraform/validate:
          name: validate
          executor: *terraform_executor
          requires:
            - init
      - terraform/plan:
          name: plan
          executor: *terraform_executor
          workspace: stg
          requires:
            - fmt
            - validate
          filters: *master_filter
      - terraform/apply:
          name: plan
          executor: *terraform_executor
          workspace: stg
          requires:
            - plan
          filters: *master_filter
  deploy:
    jobs:
      - terraform/init:
          name: init
          executor: *terraform_executor
          filters: *release_filter
      - terraform/fmt:
          name: fmt
          executor: *terraform_executor
          requires:
            - init
          filters: *release_filter
      - terraform/validate:
          name: validate
          executor: *terraform_executor
          requires:
            - init
          filters: *release_filter
      - terraform/plan:
          name: plan
          executor: *terraform_executor
          requires:
            - fmt
            - validate
          filters: *release_filter
      - hold:
          type: approval
          requires:
            - plan
          filters: *release_filter
      - terraform/apply:
          name: apply
          executor: *terraform_executor
          requires:
            - hold
          filters: *release_filter
  nightry:
    jobs:
      - terraform/init
      - terraform/fmt:
          requires:
            - terraform/init
      - terraform/validate:
          requires:
            - terraform/init
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - master
