version: 2.1
orbs:
  terraform: mafuyuk/terraform@dev:f69775b
workflows:
  verification:
    jobs:
      - terraform/fmt
      - terraform/validate
  nightry:
    triggers:
      - schedule:
          cron: "*/10 * * * *"
    jobs:
      - terraform/fmt
      - terraform/validate