version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:e9709ed

jobs:
  plan:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init
      - terraform/plan
  apply:
    executor: terraform/default
    steps:
      - checkout
      - terraform/plan

workflows:
  deploy:
    jobs:
      - plan
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold