version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:dc846cc
  aws-cli: circleci/aws-cli@0.1.9

jobs:
  plan:
    executor: terraform/default
    steps:
      - checkout
      - terraform/init:
          path: dir-check
      - terraform/plan:
          path: dir-check

workflows:
  test:
    jobs:
      - plan