version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:5448862

workflows:
  deploy:
    jobs:
      - terraform/plan:
          name: plan1
          workspace: stg
      - terraform/apply:
          name: apply
          workspace: stg
          requires:
            - plan1
      - terraform/plan:
          name: plan2
          workspace: stg
          is-destroy: true
          requires:
            - apply
      - terraform/apply:
          workspace: stg
          requires:
            - plan2