version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:955bcd9

workflows:
  deploy:
    jobs:
      - terraform/plan:
          workspace: stg
          is-destroy: true
      - hold:
          type: approval
          requires:
            - terraform/plan
      - terraform/destroy:
          workspace: stg
          requires:
            - hold