version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:3dfb2fe

workflows:
  deploy:
    jobs:
      - terraform/plan
      - hold:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          requires:
            - hold