version: 2.1
orbs:
  terraform: mafuyuk/terraform@dev:b601ef1

executors:
  terraform:
    terraform/default:
      tag: 0.11.11

workflows:
  verification:
    jobs:
      - terraform/init:
          executor: terraform
      - terraform/fmt:
          executor: terraform
          requires:
            - terraform/init
      - terraform/validate:
          executor: terraform
          requires:
            - terraform/init
  nightry:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - terraform/init:
          executor: terraform
      - terraform/fmt:
          executor: terraform
          requires:
            - terraform/init
      - terraform/validate:
          executor: terraform
          requires:
            - terraform/init