version: 2.1

orbs:
  terraform: mafuyuk/terraform@dev:8ceb406

workflows:
  deploy:
    jobs:
      - terraform/plan:
          workspace: stg
      - hold:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          workspace: stg
          requires:
            - hold